distro:
  - el7
  - fc26
substage:
  - a:
      script: 'echo TESTING STDCI DSL'
      release_branches:
        master: dummy-master
  - b:
      script:
        fromfile: 'automation/check-patch.sh'
      release_branches:
        v1.0: dummy-1.0
